AML/urls.py
from django.urls import path
from AML import views
from django.conf.urls import (
    handler400, handler403, handler404, handler500
)

app_name = 'aml'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('analysing/<int:pk>/', views.Analysing.as_view(), name='analysing'),
    path('result/<int:pk>/', views.ResultView.as_view(), name='result'),
    path('f_crawling/', views.f_crawling, name='f_crawling'),
    path('i_crawling/', views.i_crawling, name='i_crawling'),
    path('t_crawling/', views.t_crawling, name='t_crawling'),
    path('y_crawling/', views.y_crawling, name='y_crawling'),
    path('g_crawling/', views.g_crawling, name='g_crawling'),

]

handler404 = 'AML.views.handler404'
handler500 = 'AML.views.handler500'

accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('signup/', SignUp.as_view(), name='singup'),
]

django_AML/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('aml/', include('AML.urls')),
    path('admin/', admin.site.urls),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    phone_number = models.CharField(max_length=20, null=False, verbose_name='Phone number')
    employee_id = models.CharField(max_length=20, null=False, verbose_name='Employee ID')
    department = models.CharField(max_length=100, null=False, verbose_name='Department')
    employment_date = models.DateField(null=True, verbose_name='Date of employment')
    work_status = models.PositiveIntegerField(default=True, null=False)
    usage = models.PositiveIntegerField(default=0, null=False)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser
from django import forms
from datetime import datetime

year = datetime.today().year
YEARS = [x for x in range(1930, year)]


class CustomUserCreationForm(UserCreationForm):
    employment_date = forms.DateField(widget=forms.SelectDateWidget(years=YEARS))

    class Meta:
        model = CustomUser
        fields = (
            'username', 'password1', 'password2', 'first_name', 'last_name', 'email', 'phone_number', 'employee_id',
            'department', 'employment_date'
        )
        labels = {
            'username': 'ID',
        }

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)
        # help_text 안보이게
        # for fieldname in ['username', 'password1', 'password2']:
        #     self.fields[fieldname].help_text = None
        # 필수입력
        for i in self.fields:
                self.fields[i].required = True
        # bootstrap class 추가
        for i in self.fields:
            self.fields[i].widget.attrs.update({'class': 'form-control'})
        # placeholder 추가
        for i in self.fields:
            self.fields[i].widget.attrs.update({'placeholder': str(self.fields[i].label)})
        self.fields['username'].widget.attrs.update(
            {'title': self.fields['username'].help_text})
        self.fields['password1'].widget.attrs.update(
            {'title': "-password can't be too similar to your other personal information.\n" +
                      "-password must contain at least 8 characters.\n" +
                      "-password can't be a commonly used password.\n" +
                      "-password can't be entirely numeric."
             })
        self.fields['password2'].widget.attrs.update(
            {'title': self.fields['password2'].help_text})


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = ('username', 'password')

accounts/views.py
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.generic import CreateView
from django.contrib.messages.views import SuccessMessageMixin

from .forms import CustomUserCreationForm


class SignUp(SuccessMessageMixin, CreateView):
    form_class = CustomUserCreationForm
    template_name = 'accounts/signup.html'
    success_url = reverse_lazy('login')
    success_message = 'Sign up has been completed!'

    def form_valid(self, form):
        form.save()
        return super(SignUp, self).form_valid(form)

templates/accounts/login.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    <title>Sign In</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'accounts/css/login.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,300,500" rel="stylesheet">
    <style>
        .ten_body {
            background-image: url('{% static 'accounts/img/signin_bg.jpg' %}');
            background-repeat: no-repeat;
            background-size: cover;
            width: 100vw;
            height: 100vh;
            position: absolute;
            top: 0;
            left: 0;
        }

        .ten_signin_icon_id {
            background-image: url('{% static 'accounts/img/signin_id.png' %}');
        }

        .ten_signin_icon_password {
            background-image: url('{% static 'accounts/img/signin_password.png' %}');
        }
    </style>
{% endblock %}

{% block content %}
    <div class="ten_body">
        <div class="signin_form_wrapper">
            <div class="signin_form_title">
                <h2><span class="ten_font_bold">ASTER</span> Risk Management</h2>
            </div>
            <div class="signin_form_content">
                <form action="" method="post" name="signin_form" class="signin_form">
                    {% csrf_token %}
                    <div class="form-row">
                        <section class="section">
                            <div class="form-group">
                                {{ form.username }}
                            </div>
                            <div class="form-group">
                                {{ form.password }}
                            </div>
                            {% include 'messages.html' %}
                        </section>
                    </div>
                    <footer>
                        <input type="submit" id="signin_button" class="btn btn-dark btn-lg" value="Sign In">
                        <a href="{% url 'accounts:singup' %}" id="signup_button" class="btn btn-dark btn-lg">Sign
                            Up</a>
                    </footer>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script src="{% static 'accounts/js/copyJs/js/jquery.js' %}"></script>
    <script src="{% static 'accounts/js/copyJs/js/jquery.easing.1.3.js' %}"></script>
    <script>
        {% if user.is_authenticated %}
            location.replace({% url 'aml:home' %});
        {% endif %}
    </script>
{% endblock %}

templates/accounts/signup.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
    <title>Sign Up</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'accounts/css/signup.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,300,500" rel="stylesheet">
    <style>
        body {
            background-image: url('{% static 'accounts/img/signin_bg.jpg' %}');
            background-attachment: fixed;
            background-repeat: no-repeat;
            background-size: cover;
            width: 100vw;
            height: 100vh;
            position: absolute;
            top: 0;
            left: 0;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="ten_body">
        <div class="signup_form_wrapper">
            <div class="signup_form_title">
                <h2>ASTER Risk Management <span class="ten_font_bold">Register</span></h2>
            </div>
            <div class="signup_form_content">
                <form action="" method="post" name="signup_form" class="signup_form">
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="group">
                            <section class="section">
                                <div class="form-group">
                                    <h3>User Account *</h3>
                                </div>
                                <div class="form-group"
                                     data-tip="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.">
                                    {{ form.username }}
                                    {% if form.username.errors %}
                                        {% for error in form.username.errors %}
                                            <span><strong>* {{ error|escape }}</strong></span>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    {{ form.password1 }}
                                    {% if form.password1.errors %}
                                        {% for error in form.password1.errors %}
                                            <span><strong>* {{ error|escape }} <br> </strong></span>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                                <div class="form-group">
                                    {{ form.password2 }}
                                    {% if form.password2.errors %}
                                        {% for error in form.password2.errors %}
                                            <span><strong>* {{ error|escape }} <br> </strong></span>
                                        {% endfor %}
                                    {% endif %}
                                </div>
                            </section>
                            <section class="section">
                                <div class="form-group">
                                    <h3>Personal Information *</h3>
                                </div>
                                <div class="form-group">
                                    {{ form.first_name }}
                                </div>
                                <div class="form-group">
                                    {{ form.last_name }}
                                </div>
                                <div class="form-group">
                                    {{ form.email }}
                                </div>
                                <div class="form-group">
                                    {{ form.phone_number }}
                                </div>
                                <div class="form-group">
                                    {{ form.employee_id }}
                                </div>
                                <div class="form-group">
                                    {{ form.department }}
                                </div>
                                <div class="date-group">
                                    <div class="form-group">
                                        <h3>Date of employment *</h3>
                                    </div>
                                    <div class="form-group">
                                        {{ form.employment_date }}
                                    </div>
                                </div>
                            </section>
                        </div>
                    </div>
                    <footer>
                        <input type="submit" id="signup_button" class="btn btn-outline-dark btn-lg" value="Sign Up">
                    </footer>
                </form>

            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script src="{% static 'accounts/js/copyJs/js/jquery.js' %}"></script>
    <script src="{% static 'accounts/js/copyJs/js/jquery.easing.1.3.js' %}"></script>
    <script>

    </script>
{% endblock %}