AML/urls.py
from django.urls import path
from AML import views
from django.conf.urls import (
    handler400, handler403, handler404, handler500
)

app_name = 'aml'

urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('analysing/<int:pk>/', views.Analysing.as_view(), name='analysing'),
    path('result/<int:pk>/', views.ResultView.as_view(), name='result'),
    path('f_crawling/', views.f_crawling, name='f_crawling'),
    path('i_crawling/', views.i_crawling, name='i_crawling'),
    path('t_crawling/', views.t_crawling, name='t_crawling'),
    path('y_crawling/', views.y_crawling, name='y_crawling'),
    path('g_crawling/', views.g_crawling, name='g_crawling'),

]

handler404 = 'AML.views.handler404'
handler500 = 'AML.views.handler500'

django_AML/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('aml/', include('AML.urls')),
    path('admin/', admin.site.urls),
]

AML/models.py
from django.db import models
from django_countries.fields import CountryField
from accounts.models import CustomUser
from django.urls import reverse

# 링크드인 만들기

# 다른 sns 로그인 없이 돌리기.

# 인스타 로그인 없으면 팔로우 팔로워 확인 불가
# 트위터도 마찬가지
#
#


class Client(models.Model):
    analyst = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255, null=False, verbose_name='* First name')
    last_name = models.CharField(max_length=255, null=False, verbose_name='* Last name')
    government_id = models.CharField(max_length=255, null=False,  verbose_name='* Government ID')
    phone_number = models.CharField(max_length=255, null=True, verbose_name='Phone Number')
    email = models.CharField(max_length=255, null=True, verbose_name='E-mail')
    date_of_birth = models.DateField(verbose_name='Date of Birth')
    address1 = models.CharField(max_length=255, null=True, verbose_name='Address 1')
    address2 = models.CharField(max_length=255, null=True, verbose_name='Address 2')
    address_city = models.CharField(max_length=255, null=True, verbose_name='City')
    address_zip_code = models.CharField(max_length=255, null=True, verbose_name='ZIP Code')
    address_country = CountryField(verbose_name='Country', blank_label='Country Select')
    country_of_citizenship = CountryField(verbose_name='Country of Citizenship', blank_label='Country of Citizenship Select')
    company = models.CharField(max_length=255, null=True, verbose_name='Company')
    company_field_of_business = models.CharField(max_length=20, null=True, verbose_name='Company Field of Business')
    company_state = models.CharField(max_length=255, null=True, verbose_name='State')
    company_country = CountryField(verbose_name='Country', blank_label='Country Select')
    sns_facebook = models.CharField(max_length=255, null=True, verbose_name='Facebook ex) your facebook address url')
    sns_instagram = models.CharField(max_length=255, null=True, verbose_name='Instagram ex) username')
    sns_twitter = models.CharField(max_length=255, null=True, verbose_name='Twitter ex) @username')
    sns_google = models.CharField(max_length=255, null=True, verbose_name='Google ex) username@google.com')
    sns_linkedin = models.CharField(max_length=255, null=True, verbose_name='Linkedin ex) your linkedin address url')
    inserted_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        template = '{0.first_name} {0.last_name}'
        return template.format(self)


class Result(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    propensity = models.CharField(max_length=50, null=True, default=None)
    positive = models.CharField(max_length=50, null=True, default=None)
    negative = models.CharField(max_length=50, null=True, default=None)
    t_score = models.IntegerField(null=True, default=None)
    c_score = models.IntegerField(null=True, default=None)
    m_score = models.IntegerField(null=True, default=None)
    rating = models.CharField(max_length=50, null=True, default=None)
    reason = models.CharField(max_length=255, null=True, default=None)
    sns_word_cnt = models.IntegerField(null=True, default=None)
    positive_word_cnt = models.IntegerField(null=True, default=None)
    negative_word_cnt = models.IntegerField(null=True, default=None)


    def str(self):
        template = '{0.client}'
        return template.format(self)


class FacebookInfo(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    page_id = models.CharField(max_length=255, null=True, default=None)
    name = models.CharField(max_length=255, null=True, default=None)
    work = models.CharField(max_length=255, null=True, default=None)
    current_city = models.CharField(max_length=255, null=True, default=None)
    hometown = models.CharField(max_length=255, null=True, default=None)
    education = models.CharField(max_length=255, null=True, default=None)
    music_like = models.CharField(max_length=255, null=True, default=None)
    book_like = models.CharField(max_length=255, null=True, default=None)
    movie_like = models.CharField(max_length=255, null=True, default=None)
    tv_like = models.CharField(max_length=255, null=True, default=None)
    games_like = models.CharField(max_length=255, null=True, default=None)
    athletes_like = models.CharField(max_length=255, null=True, default=None)
    other_like = models.TextField(null=True, default=None)
    photo = models.IntegerField(null=True, default=None)
    inserted_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        template = '{0.client} {0.username}'
        return template.format(self)


class InstagramInfo(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    page_id = models.CharField(max_length=255, null=True, default=None)
    username = models.CharField(max_length=255, null=True, default=None)
    intro = models.CharField(max_length=255, null=True, default=None)
    homepage = models.CharField(max_length=255, null=True, default=None)
    post_cnt = models.IntegerField(null=True, default=None)
    follower_cnt = models.IntegerField(null=True, default=None)
    following_cnt = models.IntegerField(null=True, default=None)
    like_cnt = models.IntegerField(null=True, default=None)
    inserted_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        template = '{0.client} {0.username}'
        return template.format(self)


class InstagramPost(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    post_text = models.TextField(null=True, default=None)
    post_place = models.CharField(max_length=255, null=True, default=None)
    post_like = models.IntegerField(null=True, default=None)
    post_view = models.IntegerField(null=True, default=None)
    post_date = models.DateField(null=True, default=None)

    def __str__(self):
        template = '{0.client} {0.post_text}'
        return template.format(self)


class InstagramFollower(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    follower_id = models.CharField(max_length=255, null=True, default=None)
    follower_name = models.CharField(max_length=255, null=True, default=None)

    def __str__(self):
        template = '{0.client} {0.follower_name}'
        return template.format(self)


class InstagramFollowing(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    following_id = models.CharField(max_length=255, null=True, default=None)
    following_name = models.CharField(max_length=255, null=True, default=None)

    def __str__(self):
        template = '{0.client} {0.follower_name}'
        return template.format(self)


class TwitterInfo(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    username = models.CharField(max_length=255, null=True, default=None)
    page_id = models.CharField(max_length=255, null=True, default=None)
    tweet_cnt = models.IntegerField(null=True, default=None)
    following_cnt = models.IntegerField(null=True, default=None)
    follower_cnt = models.IntegerField(null=True, default=None)
    joined_date = models.DateField(null=True, default=None)
    inserted_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        template = '{0.client} {0.username}'
        return template.format(self)


class TwitterTweet(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    tweet_name = models.CharField(max_length=255, null=True, default=None)
    tweet_page_id = models.CharField(max_length=255, null=True, default=None)
    tweet_text = models.TextField(null=True, default=None)
    tweet_date = models.DateField(null=True, default=None)

    def __str__(self):
        template = '{0.client} {0.tweet_text}'
        return template.format(self)


class TwitterTrends(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    trends_name = models.CharField(max_length=255, null=True, default=None)
    trends_tweet_cnt = models.CharField(max_length=255, null=True, default=None)

    def __str__(self):
        template = '{0.client} {0.trends_name}'
        return template.format(self)


class TwitterFollower(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    follower_name = models.CharField(max_length=255, null=True, default=None)
    follower_page_id = models.CharField(max_length=255, null=True, default=None)
    follower_info = models.CharField(max_length=255, null=True, default=None)

    def __str__(self):
        template = '{0.client} {0.follower_name}'
        return template.format(self)


class TwitterFollowing(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    following_name = models.CharField(max_length=255, null=True, default=None)
    following_page_id = models.CharField(max_length=255, null=True, default=None)
    following_info = models.CharField(max_length=255, null=True, default=None)

    def __str__(self):
        template = '{0.client} {0.following_name}'
        return template.format(self)


class YoutubeInfo(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    username = models.CharField(max_length=255, null=True, default=None)
    subscribe_cnt = models.IntegerField(null=True, default=None)
    recent_video_cnt = models.IntegerField(null=True, default=None)
    comment_history_cnt = models.IntegerField(null=True, default=None)
    inserted_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        template = '{0.client} {0.username}'
        return template.format(self)


class YoutubeSubscribe(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    channel_name = models.CharField(max_length=255, null=True, default=None)
    channel_info = models.CharField(max_length=255, null=True, default=None)

AML/forms.py
from django import forms
from datetime import datetime

from .models import Client

year = datetime.today().year
YEARS = [x for x in range(1930, year)]


class ClientForm(forms.ModelForm):
    date_of_birth = forms.DateField(widget=forms.SelectDateWidget(years=YEARS))

    class Meta:
        model = Client
        fields = (
            'analyst', 'first_name', 'last_name', 'government_id', 'phone_number', 'email', 'date_of_birth', 'address1',
            'address2', 'address_city', 'address_zip_code', 'address_country', 'country_of_citizenship',
            'company', 'company_field_of_business', 'company_state', 'company_country',
            'sns_facebook', 'sns_instagram', 'sns_twitter', 'sns_google',  'sns_linkedin'
        )

    def __init__(self, *args, **kwargs):
        super(ClientForm, self).__init__(*args, **kwargs)
        for i in self.fields:

                self.fields[i].required = False
        # bootstrap class 추가
        for i in self.fields:
            self.fields[i].widget.attrs.update({'class': 'form-control'})
        # placeholder 추가
        for i in self.fields:
            self.fields[i].widget.attrs.update({'placeholder': str(self.fields[i].label)})

templates/aml/result.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    <title>RISK</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'aml/css/result.css' %}">
    <style type="text/css">


    </style>
    <link href="https://fonts.googleapis.com/css?family=Bubblegum+Sans|Nova+Mono|Roboto+Condensed" rel="stylesheet">
{% endblock %}
{% block content %}
    {% with client.result_set.all|first as result %}
        <iframe src="{% static "aml/audio/13slide.mp3" %}" allow="autoplay" style="display:none"
                id="audio_aster01"></iframe>
        <div id="wrapper">
            <div id="page-wrapper">
                <div class="header">
                    <h1 class="page-header">
                        Analyzed Result
                    </h1>
                    <ol class="breadcrumb">
                        <li><a href="{% url 'aml:home' %}">Home</a></li>
                        <li class="result_001">Analyzed Result</li>
                    </ol>
                    <div class="contentsDiv">
                        <div class="contents">
                            <div class="final_div">
                                <div class="final_triangle">
                                    <div class="one">Danger</div>

                                    <div class="two">Warning</div>

                                    <div class="three">Caution</div>

                                    <div class="four">Stability</div>
                                </div>
                            </div>
                            <div class="table_div1">
                                <table class="table">
                                    <tr>
                                        <th colspan="4" class="table_name">Personal Information</th>
                                    </tr>
                                    <tr>
                                        <th>Name</th>
                                        <td>{{ client.first_name }} {{ client.last_name }}</td>
                                        <th>Work</th>
                                        <td>{{ client.company }}</td>
                                    </tr>
                                    <tr>
                                        <th>Phone number</th>
                                        <td>{{ client.phone_number }}</td>
                                        <th>Nationality</th>
                                        <td>{{ client.country_of_citizenship }}</td>
                                    </tr>
                                    <tr>
                                        <th>Date of birth</th>
                                        <td>{{ client.date_of_birth }}</td>
                                        <th>Current city</th>
                                        <td>{{ client.address_city }}</td>
                                    </tr>
                                </table>
                                <table class="table">
                                    <tr>
                                        <th colspan="2" class="table_name">AML Hazard plot</th>
                                    </tr>
                                    <tr>
                                        <th>Rating</th>
                                        <td class="rate">{{ result.rating }}</td>
                                    </tr>
                                    <tr>
                                        <th>Reason</th>
                                        <td>{{ result.reason }}</td>
                                    </tr>
                                </table>
                                <table class="table">
                                    <tr>
                                        <th colspan="2" class="table_name">SNS data propensity</th>
                                    </tr>
                                    <tr>
                                        <th>Propensity</th>
                                        <td>
                                            Of the total {{ result.sns_word_cnt }} words extracted
                                            from {{ client.last_name }}'s
                                            SNS
                                            post,
                                            {{ result.positive_word_cnt }} positive word
                                            and {{ result.negative_word_cnt }} negative words
                                            were found. {{ client.last_name }}'s propensity analysis assessment was
                                            evaluated with a
                                            positive factor of {{ result.positive }}% and a negative factor of
                                            {{ result.negative }}%. {{ client.last_name }} is generally rated as having
                                            a {{ result.propensity }} personality.
                                        </td>
                                    </tr>
                                    <tr>
                                        <th>Positive</th>
                                        <td>{{ result.positive }}%</td>
                                    </tr>
                                    <tr>
                                        <th>Negative</th>
                                        <td>{{ result.negative }}%</td>
                                    </tr>
                                </table>
                                <table class="table">
                                    <tr>
                                        <th colspan="2" class="table_name">TCM score</th>
                                    </tr>
                                    <tr>
                                        <th>T</th>
                                        <td>{{ result.t_score }}</td>
                                    </tr>
                                    <tr>
                                        <th>C</th>
                                        <td>{{ result.c_score }}</td>
                                    </tr>
                                    <tr>
                                        <th>M</th>
                                        <td>{{ result.m_score }}</td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                        <div class="news">
                            <table class="table">
                                <tr>
                                    <th colspan="2" class="table_name">Google new Search Result</th>
                                </tr>
                                <tr>
                                    <td>There is no financial issues on this object.</td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endwith %}
{% endblock %}
{% block script %}
    <script type="text/javascript" src="{% static 'aml/js/risk.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var rating = $('.rate').text();
            if (rating === 'Stability') {
                $('.four').css('font-size', 'xx-large');
                $('.table_name').css('background', 'rgb(77, 208, 225)');
                $('th:not(.table_name)').css('color', 'rgb(77, 208, 225)')
            } else if (rating === 'Caution') {
                $('.three').css('font-size', 'xx-large');
                $('.table_name').css('background', 'rgb(100, 181, 246)');
                $('th:not(.table_name)').css('color', 'rgb(100, 181, 246)')
            } else if (rating === 'Warning') {
                $('.two').css('font-size', 'xx-large');
                $('.table_name').css('background', 'rgb(149, 117, 205)');
                $('th:not(.table_name)').css('color', 'rgb(149, 117, 205)')
            } else if (rating === 'Danger') {
                $('.one').css({'font-size': 'x-large', 'line-height': '7'});
                $('.table_name').css('background', 'rgb(240, 98, 146)');
                $('th:not(.table_name)').css('color', 'rgb(240, 98, 146)')
            }
        });
    </script>
{% endblock %}

templates/aml/risk.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    <title>RISK</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'aml/css/risk.css' %}">
    <style type="text/css">


    </style>
    <link href="https://fonts.googleapis.com/css?family=Bubblegum+Sans|Nova+Mono|Roboto+Condensed" rel="stylesheet">
{% endblock %}
{% block content %}
    <iframe src="{% static "aml/audio/13slide.mp3" %}" allow="autoplay" style="display:none" id="audio_aster01"></iframe>
    <div id="wrapper">
        <nav class="navbar-default navbar-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav" id="main-menu">
                    <li>
                        <p style="background-color : #fc6e83; color : white;	padding : 23px;">ASTER Risk
                            Management</p>
                    </li>
                    <li>
                        <a href="{% url "aml:result" %}"><i class="fa fa-002"></i> Crawling DATA</a>
                    </li>
                    <li>
                        <a class="active-menu" href="."><i class="fa fa-003"></i> Risk score</a>
                    </li>
<!--                    <li>-->
<!--                        <a href="."><i class="fa fa-004"></i> Matching</a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <a href="."><i class="fa fa-005"></i> Fraud Investigations</a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <a href="."><i class="fa fa-006"></i> Relationship with friends</a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <a href="."><i class="fa fa-007"></i> Data extract</a>-->
<!--                    </li>-->
<!--                    <li>-->
<!--                        <a href="."><i class="fa fa-007"></i> Reason code</a>-->
<!--                    </li>-->

                    <li class="sign_out">
                        <a href="{% url 'aml:home' %}"
                           style="font-size: 20px; text-align: center; background-color: #121212;">Sign
                            Out</a>
                    </li>
                </ul>

            </div>
        </nav>
        <div id="page-wrapper">
            <div class="header">
                <h1 class="page-header">
                    Risk score
                </h1>
                <ol class="breadcrumb">
                    <li><a href="{% url 'aml:home' %}">Home</a></li>
                    <li class="result_001">Risk score</li>
                </ol>
                <div class="contentsDiv">
                    <div class="intro">
                        <h1>Risk sore, Agent Reason Code Trace</h1>
                        <h2>3 Agent Sub Reports</h2>
                        <h3>{# 날짜 넣기 #}</h3>
                    </div>
                    <div class="contents">
                        <div class="final_div">
                            <div class="final_triangle">
                                <div class="one">Danger</div>

                                <div class="two">Warning</div>

                                <div class="three">Caution</div>

                                <div class="four">Stability</div>
                            </div>
                        </div>
                        <div class="table_div1">
                            <table class="table">
                                <caption>* FACEBOOK DATA BASE</caption>
                                <tr>
                                    <th colspan="4" class="table_name">Personal Information</th>
                                </tr>
                                <tr>
                                    <th>Name</th>
                                    <td>{{ facebook.username }}</td>
                                    <th>Address</th>
                                    <td>{{ facebook.address1 }}</td>
                                </tr>
                                <tr>
                                    <th>Gender</th>
                                    <td>{{ facebook.gender }}</td>
                                    <th>Education</th>
                                    <td>{{ facebook.university1 }}</td>
                                </tr>
                                <tr>
                                    <th>Date of birth</th>
                                    <td>{{ facebook.birthday }}</td>
                                    <th>Company</th>
                                    <td>{{ facebook.company1 }}</td>
                                </tr>
                            </table>
                            <table class="table">
                                <caption>* AML DATA BASE</caption>
                                <tr>
                                    <th colspan="2" class="table_name">AML Hazard plot</th>
                                </tr>
                                <tr>
                                    <th>Rating</th>
                                    <td>{{ reason.rating }}</td>
                                </tr>
                                <tr>
                                    <th>Reason</th>
                                    <td>{{ reason.reason }}</td>
                                </tr>
                                <tr>
                                    <th>High frequency word</th>
                                    <td>asdsadsad</td>
                                </tr>
                            </table>
                            <table class="table">
                                <caption>* SNS DATA BASE</caption>
                                <tr>
                                    <th colspan="2" class="table_name">SNS data propensity</th>
                                </tr>
                                <tr>
                                    <th>Propensity</th>
                                    <td>
                                        Of the total {{ word_cnt }} words extracted from {{ facebook.username }}'s SNS
                                        post,
                                        {{ posi }} positive and {{ nega }} negative words
                                        were found. {{ facebook.username }}'s propensity analysis assessment was
                                        evaluated with a
                                        positive factor of {{ result.positive }}% and a negative factor of
                                        {{ result.negative }}%. {{ facebook.username }} is generally rated as having
                                        a {{ result.propensity }} personality.
                                    </td>
                                </tr>
                                <tr>
                                    <th>Positive</th>
                                    <td>{{ result.positive }}%</td>
                                </tr>
                                <tr>
                                    <th>Negative</th>
                                    <td>{{ result.negative }}%</td>
                                </tr>
                            </table>
                            <table class="table">
                                <tr>
                                    <th colspan="2" class="table_name">TCM score</th>
                                </tr>
                                <tr>
                                    <th>T</th>
                                    <td>{{ result.t_score }}</td>
                                </tr>
                                <tr>
                                    <th>C</th>
                                    <td>{{ result.c_score }}</td>
                                </tr>
                                <tr>
                                    <th>M</th>
                                    <td>{{ result.m_score }}</td>
                                </tr>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}
{% block script %}
    <script type="text/javascript" src="{% static 'aml/js/risk.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            var rating = '{{ reason.rating }}';
            if (rating === 'Stability') {
                $('.four').css('font-size', 'xx-large');
                $('.table_name').css('background', 'rgb(77, 208, 225)');
                $('th:not(.table_name)').css('color', 'rgb(77, 208, 225)')
            } else if (rating === 'Caution') {
                $('.three').css('font-size', 'xx-large');
                $('.table_name').css('background', 'rgb(100, 181, 246)');
                $('th:not(.table_name)').css('color', 'rgb(100, 181, 246)')
            } else if (rating === 'Warning') {
                $('.two').css('font-size', 'xx-large');
                $('.table_name').css('background', 'rgb(149, 117, 205)');
                $('th:not(.table_name)').css('color', 'rgb(149, 117, 205)')
            } else if (rating === 'Danger') {
                $('.one').css({'font-size': 'x-large', 'line-height': '7'});
                $('.table_name').css('background', 'rgb(240, 98, 146)');
                $('th:not(.table_name)').css('color', 'rgb(240, 98, 146)')
            }
        });
    </script>
{% endblock %}